### PR TITLE
React 0.14

### LINKED ISSUE #30: React 0.14
This is going to break a lot of stuff :sob:. At a first glance I believe we are going to need to find a method of retrieving the component of a DOM node (i.e. the reverse of `React.findDOMNode`).

### PR DESCRIPTION
**Pull request by oliverwoodings**
This PR updates react-test-tree to support React 0.14. This will be a breaking update for anyone using React 0.13 or lower, so I propose we release it as v0.3.0. I also propose that we release when 0.14 is also officially released.

* Split tree nodes into two types: `TestNode` and `TestClassNode`
* `TestNode`s represent plain HTML elements, whereas `TestClassNode`s represent instances of React components
* Only `TestClassNode`s have the code for handling refs/refCollections and their associated logic
* `getDOMNode` is abstracted into a separate utility method in order to handle different types of element
* The ref tree walk has now been updated to handle React's new ref structure. Unfortunately this is not very clean

Still to do: 

- [x] Add HOC support
- [x] Pull in changes to README
- [x] Handle ref name clashes
- [x] Decide on value prop
- [x] Simulate library tests
- [x] refCollections should work on composites
- [x] Document breaking changes and how to migrate
- [x] Release rc1
- [x] Complete empty tests, add additional tests
- [x] Add support for stateless components
- [x] Always wrap input with additional component so we can hijack render
- [x] Refactor to use `testRef` and `testRefCollection` instead of `ref` and `refCollection`
- [x] Update docs to reflect new API changes
- [x] Document how state changes are async
- [x] Children should retain their type; don't always convert them to an array
- [x] Investigate HoC/stubbing issue (add more tests on it)
- [x] Fix owner being incorrectly changed
- [x] Remove saucelab keys from travis.yml
- [x] Ensure testRef prop is fully removed from the props object
- [x] Add support for material-ui and react-bootstrap components
- [x] Ensure owner is always set to original node's owner when cloning (including stub situations)

Closes #30 #47 #43 #39 #24 #48 #45

### CODE REVIEW

**Comment by oliverwoodings** [comment]
Need to resolve #36 before this can be merged

**Comment by joeybaker** [comment]
Just checking… is there still a plan to merge this?

**Comment by oliverwoodings** [comment]
Hi - yeah there's still a bit more work to be done, but I'm hoping to do it
this week.

**Comment by oliverwoodings** [comment]
@joeybaker @aguestuser @doctyper this has been released as 1.0.0-rc1. Please install like so:

```npm install react-test-tree@1.0.0-rc1```

Could you give it a whirl for me? Thanks! Check out the README and CHANGELOG to see what has changed.

**Comment by joeybaker** [comment]
I likely won't have time to look at this until Friday, but I will, and thank you for the work!!

**Comment by aguestuser** [comment]
Yay! Such great news! Happy to take a look and will likely have time to do so somewhere in the Thur/Fri range.

**Comment by joeybaker** [comment]
I gave this a quick tryout today. Unfortunately, I'm getting an error. Here's a repo. You can run the tests with `npm test`

**Comment by oliverwoodings** [comment]
@joeybaker thanks for trying it out. Did you forget to put a link in?

**Comment by joeybaker** [comment]
Whoops! Sorry about that. Here's the repo https://github.com/joeybaker/react-element-query/tree/react-0-14?files=1 relevant code is in the `react-0-14` branch

**Comment by oliverwoodings** [comment]
Ok this happens because we now always need to wrap the component's render function before rendering it. This doesn't work in your case because you are passing a <div /> as the top level component. I should be able to fix this by always wrapping the testTree input in a proper component.

**Comment by joeybaker** [comment]
:+1: thanks!

**Comment by oliverwoodings** [comment]
@joeybaker rc2 has been released, please give it a whirl it should fix your issue!

**Comment by oliverwoodings** [comment]
@joeybaker just released rc3 which fixes rc2 - please try that out :)

**Comment by joeybaker** [comment]
@oliverwoodings my day became very crazy. Will look tomorrow. Sorry for the delay!

**Comment by joeybaker** [comment]
@oliverwoodings Okay, I tried rc3, and I'm seeing a new error:



Relevant bit of the code:

```js
  const smallTree = testTree((<div style={{width: 200}} refCollection="container">
    <ElementQuery sizes={sizes}>
      <h1>hi</h1>
    </ElementQuery>
  </div>), {mount: true})
  const smallEl = smallTree.container[0].element
```

**Comment by oliverwoodings** [comment]
@joeybaker your refCollection prop there is not contained inside a component so it doesn't belong to anything. If you want to render it like that you need to set the `wrap` config option to true.


react-test-tree@1.0.0-rc4 has been released with support for the new `testRef` and `testRefCollection` support.

**Comment by doctyper** [comment]
@oliverwoodings: Just tried out rc4, the new `testRef` and `testRefCollection` API works great.

Question, in rc3 it was possible to add a ref to a child and have that ref be accessible from `react-test-tree`. E.g.:

```
const someElementTree = testTree(
    <SomeElement>
        <div ref="testChild">Test Child</div>
    </SomeElement>
);

const testChildRef = someElementTree.get("testChild");
expect(testChildRef).to.exist; // passes rc3, fails rc4
```

This no longer works in rc4 (I also tried changing `ref` -> `testRef`. No joy.)

Is this by design or a bug?

**Comment by Blystad** [comment]
Hmm, I upgraded all my dependencies today, and my application works fine. Now I'm working on getting the tests up and running as well, and I see this error:

```
Error: Invariant Violation: onlyChild must be passed a children with exactly one child.
    at invariant (base/test/all-tests.js:15071:16)
    at Object.onlyChild [as only] (base/test/all-tests.js:33443:85)
    at Transition.render [as __rttOldRender] (base/test/all-tests.js:57454:46)
    at Transition.renderProxy [as render] (base/test/all-tests.js:35497:51)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (base/test/all-tests.js:21530:35)
    at ReactCompositeComponentMixin._renderValidatedComponent (base/test/all-tests.js:21550:33)
    at ReactPerf.measure.wrapper (base/test/all-tests.js:15345:22)
    at ReactCompositeComponentMixin.mountComponent (base/test/all-tests.js:21163:31)
    at ReactPerf.measure.wrapper [as mountComponent] (base/test/all-tests.js:15345:22)
    at Object.ReactReconciler.mountComponent (base/test/all-tests.js:19473:36)
```

Running on rc4.

I'm not doing anything special, just rendering this in a ES6 class extending React.Component:
```
        <Nav className="nav-icon" bsStyle="pills" stacked ref="items">

        </Nav>
```
(From react-bootstrap) (I usually have stuff inside the Nav element, but for the sake of testing I removed it).

I debugged the code, and `this.props.children` is provided as an array with length = 1, while the React.Children.only expects a object.

**Comment by joeybaker** [comment]
I ran into that too. It was my assumption that react 0.14 changed the behavior of children to always be an array, but I didn't consider that test tree might be at fault.

**Comment by joeybaker** [comment]
@oliverwoodings got it thanks! I missed that `wrap` was added in 1.0. 

I just gave rc4 a shot, and everything looks good!

**Comment by joeybaker** [comment]
A suggestion: it might be worth adding a migration-guide doc for 1.0.

Based on the changelog and my own notes, I think these are the main points:

```
* `.get` && `getIn` instead of direct property access
* `wrap` option to use refs on an element passed directly to test tree
* `testRef` and `testRefCollection` instead of just `ref` and `refCollection`
```

Would you accept a PR that created this doc?

**Comment by Blystad** [comment]
Hmm...I can't get a decorated component to properly work...

1) The component has a ref which is supposed to be stubbed out, that part seems to be broken because of reassignment bug here: https://github.com/QubitProducts/react-test-tree/blob/react0.14/lib/testTree.js#L73-L79 (const ftw!)

2) I have declared `innerComponentRef` and `innerTestRef`, and the fields inside the component I have put in `testRef`, as it should be. But I can't get it to work.

FWIW I use react-bootstrap. The component works fine in the app, but breaks in tests... Please try reproducing, and if unable I can try creating a test case.

**Comment by doctyper** [comment]
@Blystad I'm having the same issue. test-tree seems to lose refs when components get HoC wrapped / decorated.

**Comment by oliverwoodings** [comment]
@doctyper you need to use the new `wrap` option for that scenario to work. As with the old `ref` syntax, `testRef`s and `testRefCollection`s have to 'belong' to a composite component (i.e. they need to be returned from the `render` function of a component class). In your example there you are calling testTree with elements that aren't contained inside a component class. Specifying `wrap: true` in the testTree options will cause testTree to wrap it for you :)

@joeybaker check out the readme on the react0.14 branch, there is a section in there on migrating to 1.0. Feel free to add to it!

@Blystad @joeybaker regarding children being an array, this is a bug in test-tree that I need to address. For some reason I assumed making children always an array wouldn't be a problem, but I now see the issue with that! https://github.com/QubitProducts/react-test-tree/blob/react0.14/lib/testTree.js#L151

@Blystad not sure I follow you about the stubbing out part - what is the reassignment bug?

I'll check out the HoC issues, see if I can reproduce anything.

**Comment by Blystad** [comment]
@oliverwoodings I'm not sure the re-assignment is a bug, but it certainly looks strange to reassign a function argument multiple places.

Any chance you can look into the HOC and React.Children issue soon? 2/3 of my tests are currently broken :(

Thanks for your hard work!

**Comment by oliverwoodings** [comment]
Yep planning to look into those today. Been a bit hectic here, sorry I haven't got round to it sooner!

**Comment by oliverwoodings** [comment]
@Blystad @joeybaker the children issue is fixed on the react0.14 branch. Working on the HoC/stubbing issue now

**Comment by oliverwoodings** [comment]
@Blystad @doctyper i'm not able to replicate the HoC issue, and all the tests are passing for stubbing/HoC. Could you make a test case please?

**Comment by Blystad** [comment]
Alright, will do.

**Comment by Blystad** [comment]
https://github.com/Blystad/issue-RTT-31

Here you go. I stripped away as much as I feel confident about removing.

What I'm doing (and which worked great on 0.13), is inspired by [redux-form](https://github.com/erikras/redux-form).

I have a decorator which accepts some options:
```
{
    form: <formName>,
    fields: ['fieldA', 'fieldB', 'fieldC'],
    validator: function,
}
```

The decorator then passes on a datastructure in the `fields` prop, which contains the properties I want to assign to each input field:
```
          onChange: this.onChange.bind(this),
          name: fieldName,
          testRef: fieldName,
          value: this.props.values[fieldName],
          checked: this.props.values[fieldName],
```

I test this using both autogenerated and written tests. The auto generated ones are there to ensure that the form is hooked up correctly, and the written tests to ensure special form behaviour.

**Comment by oliverwoodings** [comment]
@Blystad i'm not able to install your test setup i'm afraid, get this error:

screen shot 2015-11-20 at 14 11 59

(i've checked, that file isn't there before i run npm install)

**Comment by Blystad** [comment]
Try using a newer version of Node. I use 4 I think.

**Comment by oliverwoodings** [comment]
Ok will do

**Comment by oliverwoodings** [comment]
Ok got it running, but it's proving quite hard to debug. Will update you as I go.

**Comment by Blystad** [comment]
Great, thanks

**Comment by oliverwoodings** [comment]
@Blystad worked it out! Here: https://github.com/Blystad/issue-RTT-31/blob/master/src/main/js/policy/PolicyDecorator.jsx#L63 you are setting the testRef, then spreading the props onto the component. Props actually contains `{ testRef: undefined }`, which overrides the previous testRef you set. If you move the `testRef` to after you spread the props it will work.

The reason this happens is because we have to 'delete' the testRefs from parents so they don't accidentally propagate to children. I'm currently doing this by setting testRef to be undefined when cloning, which is what is causing this adverse behavior. We have to set it to undefined because react does a shallow merge when using React.cloneElement. I'm going to have to find another way to 'remove' the prop (probably by manually recreating the element instead of cloning it).

**Comment by Blystad** [comment]
Aha, great, I'll test that tomorrow :) Thanks

**Comment by Blystad** [comment]
Tested it, and you were right.

However, the `onChange` tests still fail. If I change the inputs to normal HTML inputs, it's fine. Bootstrap `Input` however, does not work.

**Comment by oliverwoodings** [comment]
@Blystad this is not directly a problem with RTT. You are calling simulate on react-bootstrap's `<Input />` component - this is not actually an input DOM node, hence why it doesn't work. See this thread: https://github.com/react-bootstrap/react-bootstrap/issues/297 - to simulate changes on a react-bootstrap component you have to call it's `getInputDOMNode()` method. We used to invisibly support this quirk in RTT by checking if an element had the `getInputDOMNode` method, but I removed it in the new version since I want to try and keep RTT as pure and unbiased as possible. Maybe I should add it back, though...

**Comment by wbecker** [comment]
Hey Oli - it's also a similar issue with Material UI -
http://material-ui.com. It's a pain - not sure how to fix it, as those
components get quite complicated. I'm testing the onChange prop which is
passed in, but would be nice if there were a common way to handle these
things..

**Comment by oliverwoodings** [comment]
@wbecker does material-ui expose similar kinds of methods?

**Comment by wbecker** [comment]
No, it's pretty black box. I would have thought though that the point of
RTT with regards to 3rd party libraries should be to make it easy to ensure
that callbacks happen, not that some action on the DOM triggers a callback.

Like if have a thing like <div><SomeMaterialUIComponent
onChange={this.changeCallback} /></div> what I would want to test is that
changeCallback gets called (with the expected arguments).

From a Unit test PoV you shouldn't care under what circumstances it gets
called - just that your component that uses it handles the onChange event.

From an Integration test PoV you do care about this, and if the underlying
component changes from one version to another (eg it provides different
arguments) then you will have some issues. I'm not sure how to test this
though, because this implies that you can create the right scenario for
that callback to be triggered in the test... This is obvs tricky - it might
be simple if your component if just wrapping a Select or something, but
will get a lot more complicated as the complexity of the 3rd party
component changes. In these cases, what can you do? So in the general case
maybe its best to focus on allowing the Unit test use case?

**Comment by oliverwoodings** [comment]
> No, it's pretty black box. I would have thought though that the point of
> RTT with regards to 3rd party libraries should be to make it easy to ensure
> that callbacks happen, not that some action on the DOM triggers a callback.

How is RTT meant to know what a callback is meant to be called with? We can't assume that just because a component has a prop called `onChange` that it is expecting to be invoked like a native JavaScript onChange handler.

> Like if have a thing like <div><SomeMaterialUIComponent
> onChange={this.changeCallback} /></div> what I would want to test is that
> changeCallback gets called (with the expected arguments).

Again - how is RTT meant to know what 'expected' arguments are? I would also argue that if you are testing for expected arguments then you are doing an integration test, not a unit test. By testing the arguments you are testing the third party component.

> From a Unit test PoV you shouldn't care under what circumstances it gets
> called - just that your component that uses it handles the onChange event.

I agree, but if that is the case then maybe you should just be stubbing out the third party component and triggering the onChange yourself. If you just want to make sure that `changeCallback` is invoked, can't you just manually invoke the prop yourself:

```jsx
var tree = testTree(<FooComponent />);
var spy = sinon.spy(tree.element, "changeCallback");
tree.get("thirdPartyComponent").getProp("onChange")("foo");
expect(spy).to.have.been.calledWith("foo");
```

And perhaps combine this with stubbing to make some kind of generic replacement component?

**Comment by Blystad** [comment]
I quickly checked the source and I guess this is what you're looking for @oliverwoodings 

```
  getInputNode() {
    return ReactDOM.findDOMNode(this.refs.input);
  },
```

[https://github.com/callemall/material-ui/blob/master/src/enhanced-textarea.jsx#L122](https://github.com/callemall/material-ui/blob/master/src/enhanced-textarea.jsx#L122)

**Comment by wbecker** [comment]
>How is RTT meant to know what a callback is meant to be called with?

Exactly! That's what I was trying to differentiate between unit and
integration tests. You have to provide that yourself which is all pretty
lame.

It would be nice if there were a common way to get things triggered, to
make things like this easier... Like a HoC or something, kind of needs to
be a Lower order Component that lives inside that allows you to trigger
things as needed, so that it provides the right arguments. But that's not a
thing, but maybe there needs to be some common API that React components
can use so that you can do integration tests in a similar way all the time?
(I can't see it really picking up much steam though...)

That code is pretty much what I do. It's not fantastic but it allows you to
do some kind of TDD.

**Comment by Blystad** [comment]
On another note, I'm trying this:

```
const inputDOMNode = root().get(item).element.getInputDOMNode();
expect(inputDOMNode, 'inputDOMNode').to.exist;
```

but, while I'm able to call `getInputDOMNode` the return value is `undefined`. I tried checking `root().get(item).element.refs` but that was an empty object.

Ideas?

**Comment by oliverwoodings** [comment]
@wbecker interesting stuff, although I can't really see how RTT can solve what you want.

@Blystad I'll check it out

**Comment by oliverwoodings** [comment]
@Blystad try installing directly from the react0.14 branch. I've pushed the updates for react-bootstrap integration, all your tests pass now:

screen shot 2015-11-22 at 16 30 18

Will hopefully have this released as an RC today.

**Comment by oliverwoodings** [comment]
@Blystad 1.0.0-rc5 has been released, please give it a whirl. I'm hoping this is our final rc needed before I can finally merge this!

**Comment by Blystad** [comment]
:disappointed: I wish I could just put forth the :+1: and say shipit :shipit: but I found another, (damn) bootstrap related, bug:

When adding `wrapperClassName` and `labelClassName` to a `Input` component, the test fails. See updated test-case @ https://github.com/Blystad/issue-RTT-31/commit/b57beb53341f7b5510107cc0707e98e7a473a2d7

**Comment by oliverwoodings** [comment]
Wow how odd! I'll check it out

**Comment by oliverwoodings** [comment]
I've narrowed the issue down to the `wrapperClassName` prop which causes react-bootstrap to wrap the input children in a div. It is definitely caused by rtt somehow, just tring to work out why.

**Comment by oliverwoodings** [comment]
Worked out why. I switched to manually cloning the element using `React.createElement` with the old element type and new props/children (to fix the issue of `testRef` propagating as undefined) however this had the adverse affect of changing the `owner` of the elements, resulting in refs being assigned incorrectly. I've come up with a hacky fix for now, will release as an rc.

**Comment by oliverwoodings** [comment]
@Blystad 1.0.0-rc6 released, should solve your issues

**Comment by oliverwoodings** [comment]
Released 1.0.0-rc7 which fixes stubbing refs being passed through

**Comment by oliverwoodings** [comment]
Ok I'm going to merge and release this. I'm confident now that all the core issues are resolved and anything else will just be edge cases that can be fixed with small patches.

**Comment by oliverwoodings** [comment]
screen shot 2015-11-23 at 14 49 44

**Comment by joeybaker** [comment]
Thanks for all the hard work @oliverwoodings!

**Comment by Blystad** [comment]
Awesome, great work, thanks :)

**Comment by austinpray** [comment]
This is working great on my side! Thank you!

**Pull request merged**
