### PR TITLE
Use innerText if the element doesn't have a value attribute

### PR DESCRIPTION
**Pull request by jhollingworth**

### CODE REVIEW

**Comment by jhollingworth** [comment]
Builds :green_heart: now, OK to merge?

**Comment by oliverwoodings** [comment]
:+1: can you add a quick note about it in the README?

**Comment by jhollingworth** [comment]
done

**Comment by oliverwoodings** [comment]
:shipit:

**Comment by jhollingworth** [comment]
@oliverwoodings can you publish?

**Pull request merged**
